use_frameworks!

platform :ios, '13.0'

target 'TOSClientKitSwiftDemo_Example' do
  pod 'TOSClientKit', :path => '../'
  pod 'MBProgressHUD'
  pod 'SDWebImage', '5.21.0'
end


# 所有三方SDK最小支持小于iOS 13的都改成iOS 13
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 13.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
      
      # 移除 CoreAudioTypes
      if config.build_settings['OTHER_LDFLAGS']
        config.build_settings['OTHER_LDFLAGS'].delete('-framework CoreAudioTypes')
      end
      
      # 其他必要设置
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
